name: www.realestate.com.au
favicon: null
layout_spectrum: 0.2262451744172722
typography_spectrum: 0.20954113150946796
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9547119119670242
  lightness: 0.2383300494402647
  saturation: 0.29894816037267447
  rhythmicContrast: 0.8624856378883123
purpose: []
